/* Generated By:JavaCC: Do not edit this line. ISO8601ParserConstants.java */
package com.sun.msv.datatype.xsd.datetime;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ISO8601ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int digit = 1;
  /** RegularExpression Id. */
  int digits = 2;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<digit>",
    "<digits>",
    "\".\"",
    "\"-\"",
    "\"P\"",
    "\"T\"",
    "\"Y\"",
    "\"M\"",
    "\"D\"",
    "\"H\"",
    "\"S\"",
    "\"Z\"",
    "\"+\"",
    "\":\"",
  };

}
